#!/usr/bin/env node
// Frontend ABIs for the v3 contracts the web app calls directly, generated from the forge build artifacts.
// Usage (after `forge build`): node script/v3/export-abis.mjs          # writes web/lib/v3-abis.ts
//                              node script/v3/export-abis.mjs --check  # exits 1 if the file is stale
// Addresses come from the DeployV3 manifest (script/v3/out/v3-<chainId>.json, `.contracts.<Name>`).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(root, 'web', 'lib', 'v3-abis.ts');

// [export name, artifact file, contract]
const CONTRACTS = [
  // r8: one-step native USDC -> NVDA.sol (pool A) -> meme and back (quote/swapExactIn); address
  // `.contracts.V3MultiHopRouter`, NVDA only.
  ['v3MultiHopRouterAbi', 'V3MultiHopRouter.sol', 'V3MultiHopRouter'],
  // r8: pool A state for the quote page (currentTick/liquidity/tickLower/tickUpper + RangeSet/PricePushed/Restock).
  ['stockPoolVaultAbi', 'StockPoolVault.sol', 'StockPoolVault'],
  // r7: status/peek/execPrice for showing whether a stock is tradable now and at what price.
  ['solonStockOracleAbi', 'SolonStockOracle.sol', 'SolonStockOracle'],
  // r7: the creator's payout-stock list shown at launch.
  ['launchPayoutChoiceAbi', 'LaunchPayoutChoice.sol', 'LaunchPayoutChoice'],
];

function abiOf(file, name) {
  const p = join(root, 'out', file, `${name}.json`);
  if (!existsSync(p)) throw new Error(`missing artifact ${p}: run forge build first`);
  return JSON.parse(readFileSync(p, 'utf8')).abi;
}

const lines = [
  '// GENERATED by script/v3/export-abis.mjs from forge artifacts (out/). Do not edit by hand.',
  '// Regenerate after contract changes; `node script/v3/export-abis.mjs --check` fails when stale.',
];
for (const [exportName, file, name] of CONTRACTS) {
  lines.push(`export const ${exportName} = ${JSON.stringify(abiOf(file, name))} as const;`);
}
const text = lines.join('\n') + '\n';

if (process.argv.includes('--check')) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (cur !== text) {
    console.error('web/lib/v3-abis.ts is stale: run node script/v3/export-abis.mjs');
    process.exit(1);
  }
  console.log('web/lib/v3-abis.ts up to date');
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT} (${CONTRACTS.length} ABIs)`);
}
